services:

  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-data:/var/lib/docker
    networks:
      - jenkins-network

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "127.0.0.1:8080:8080"

    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client

    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro

    networks:
      - jenkins-network

    depends_on:
      - docker

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:
  docker-data:

networks:
  jenkins-network:
    driver: bridge
